# Serving Configuration for Dry-Wet Road Classifier

# Image preprocessing configuration
training:
  img_size: 600  # Image size for preprocessing (must match training configuration)

# Normalization configuration (match training preprocessing)
normalization:
  mean: [0.485, 0.456, 0.406]  # ImageNet normalization mean
  std: [0.229, 0.224, 0.225]   # ImageNet normalization std